gui:
  theme:
    activeBorderColor:
      - '#FBF1C7'
      - bold
    inactiveBorderColor:
      - '#A89984'
    searchingActiveBorderColor:
      - '#FBF1C7'
    optionsTextColor:
      - '#928375'
    selectedLineBgColor:
      - '#32302F'
    cherryPickedCommitFgColor:
      - '#32302F'
    cherryPickedCommitBgColor:
      - '#32302F'
    selectedRangeBgColor:
      - '#313244'
    unstagedChangesColor:
      - '#CC241D'
    defaultFgColor:
      - '#FBF1C7'
  commitLength:
    show: false
  wrapLinesInStagingView: false
  showRootItemInFileTree: false
  showBottomLine: false
  showPanelJumps: false
  commitHashLength: 0
  nerdFontsVersion: '3'
  filterMode: 'fuzzy'
  border: 'single'
os:
  editPreset: 'nvim'
